### ISSUE TITLE
English models

### ISSUE THREAD

**Issue by tek** [erickrf/nlpnet#1]
Hey there, any chance there are models for the English language available, or is this only usable in Portuguese yet?

**Comment by kiran-surya** [comment]
Hi Erick,

I'm facing following issue:
Reading text...
Loading vocabulary
Done. Dictionary size is 129998 types
Creating new network...
Loading word vectors...
Generating capitalization features...
Generated 5 feature vectors with 5 features each.
Generating suffix features...
Generated 457 feature vectors with 5 features each.
Generating gazetteer features...
Generated 2 feature vectors with 5 features each.
Generated 2 feature vectors with 5 features each.
Generated 2 feature vectors with 5 features each.
Generated 2 feature vectors with 5 features each.
Created new network with the following layer sizes: 400, 300, 17
Starting training with 22138 sentences
Network weights learning rate: 0.000100
Feature vectors learning rate: 0.010000
Tag transition matrix learning rate: 0.010000
Training for up to 40 epochs
Traceback (most recent call last):
  File "bin/nlpnet-train.py", line 267, in <module>
    train(text_reader, args)
  File "bin/nlpnet-train.py", line 210, in train
    args.iterations, report_intervals, args.accuracy)
  File "network.pyx", line 574, in nlpnet.network.Network.train (nlpnet/network.c:8601)
  File "network.pyx", line 636, in nlpnet.network.Network._train_epoch (nlpnet/network.c:9546)
  File "network.pyx", line 310, in nlpnet.network.Network._tag_sentence (nlpnet/network.c:5898)
ValueError: all the input arrays must have same number of dimensions

**Comment by erickrf** [comment]
Hi @kiran-surya , 

your log output has "gazetteer features", which is not part of my original nlpnet. I suppose you are using some fork with NER functionalities?

**Comment by kiran-surya** [comment]
Hi @erickrf,

Thanks for your prompt reply. Yes, i'm using NER functionality, but that should not effect vector dimensions, correct?

**Comment by erickrf** [comment]
No, it shouldn't, but I can't help much if the code is from a fork. The problem you describe (at least with line numbers in the stack trace) doesn't apply to the current nlpnet version.

**Comment by kiran-surya** [comment]
Thank you.

**Comment by nshresthan** [comment]
Hi Erick
I have installed nlpnet successfully. But when I try to set the path (folder containing models), it always gives error ": No such file or directory"
I used both method like
$ nlpnet-tag.py srl --data /media/backup/NLP_tool/nlpnet/data --lang pt

and also in python command line
>>> tagger.set_data_dir('/media/backup/NLP_tool/nlpnet/data')

Both commands gives the same error. 
/media/backup/NLP_tool/nlpnet/data folder contains all the .zip model file and also extracted file. I also give the path of extracted file like: '/media/backup/NLP_tool/nlpnet/data/pos-pt'

Could you please suggest me where I went wrong? 

Thanks in advance. 
Shrestha

**Comment by erickrf** [comment]
Hi Shrestha,

the data parameter value should be the path to the uncompressed folder, i.e. the contents of that folder should be vocabulary.txt, .npz files etc.

If you still get the error, please copy the full error message from nlpnet. Also, check if you are using the most recent version of code and data (they haven't been updated in some months, though).

**Comment by nshresthan** [comment]
Hi Erick, 
Thanks for the reply. 
nlpnet.set_data_dir('/media/backup/NLP_tool/nlpnet/data/pos-pt')
works from python and also I can now run POS and SRL example for Portuguese language. 
But if I try to set the language, then it gives error: 

>>> nlpnet.set_data_dir('/media/backup/NLP_tools/nlpnet/data/pos-pt', language='pt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: set_data_dir() got an unexpected keyword argument 'language'

**********************************
Next issue: 
I tried to used English dependency as given in example. I have set data dir successfully. But when I tried to parse the example sentence it give error:

>>> parser = nlpnet.DependencyParser('/media/backup/NLP_tools/nlpnet/data/dependency', language='en')
>>> parsed_text = parser.parse('The book is on the table.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nlpnet/taggers.py", line 336, in parse
    parsed = self.parse_sentence(sent)
  File "/usr/local/lib/python2.7/dist-packages/nlpnet/taggers.py", line 361, in parse_sentence
    tokens = self.pos_tagger.tag_tokens(tokens, return_tokens=True)
  File "/usr/local/lib/python2.7/dist-packages/nlpnet/taggers.py", line 444, in tag_tokens
    answer = self.nn.tag_sentence(converted_tokens)
  File "nlpnet\network.pyx", line 268, in nlpnet.network.Network.tag_sentence (nlpnet/network.c:5297)
  File "nlpnet\network.pyx", line 294, in nlpnet.network.Network._tag_sentence (nlpnet/network.c:5754)
  File "nlpnet\network.pyx", line 217, in nlpnet.network.Network._create_sentence_lookup (nlpnet/network.c:4529)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

Could you please let me know where things goes wrong? 

Thanks 
Shrestha

**Comment by nshresthan** [comment]
Hi Erick
Sorry for many issues. 
My next issue is, I could not find the training script(nlpnet-train.py) that is supposed to be script folder but could not find it. 
is train_srl.py in "srl" is training script? I am bit doubt on it. 
OR, could you please point me, from where can I download it? 

*****************************************
next issue is I am not able to run the stand alone script from command line. for eg. 

$ nlpnet-tag.py pos --data /media/backup/NLP_tools/nlpnet/data/pos-pt/ --lang pt
: No such file or directory

Did I installed nlpnet wrongly or wrong version. But it works on python (As I mentioned in earlier post). 

Thanks 
Shrestha

**Comment by hamotahari** [comment]
@nshresthan I use Linux and  have had this problem. It solved by converting the DOS file format to Linux (by `sudo fromdos /usr/local/bin/nlpnet-*` command).
I converted all nlpnet-*.py files.
