### ISSUE TITLE
Problem recognizing accents and special characters

### ISSUE THREAD

**Issue by renatofmartins** [erickrf/nlpnet#10]
Hi,
I am having problem is with the file encoding. When I send a word with accent, like "caçar", it recognize like "(u'ca\xc3\xa7ar', u'NPROP')", not like a Verb. Any idea?

Thank's

Renato

**Comment by erickrf** [comment]
It seems the input string was originally UTF-8 interpreted as latin-1 (producing Ã§ for the UTF-8 ç character) before converting to unicode:

    >>> s = u'ca\xc3\xa7ar'
    >>> print s
    caÃ§ar

The nlpnet command line scripts expect files to be encoded in UTF-8. The tagger functions expect unicode strings. 

By the way, I just tested it:

    >>> import nlpnet
    >>> nlpnet.set_data_dir('pos-pt/')
    >>> tagger = nlpnet.POSTagger()
    >>> tagger.tag(u'caçar')
    [[(u'ca\xe7ar', u'V')]]

**Comment by renatofmartins** [comment]
I got it. Thanks.

Just one more question. Do you know if it's possible to convert a list to UTF-8 or remove the special characters? I have tried to use the encode function, but is not working with the result of the tagger function.
I need the word "caçar" for tagging it correctly, but i need it as "cacar", without the "ç" to classify the text.

i.e.:
[[(u'ca\xe7ar', u'V')]]  =>> [[(u'cacar', u'V')]]

Thanks a lot!

**Comment by erickrf** [comment]
I think you are mixing up some concepts. A unicode string like u'ca\xe7ar' can be encoded in UTF-8 using the encode function:

    >>> s = u'ca\xe7ar'
    >>> s.encode('utf-8')
    'ca\xc3\xa7ar'

However, you usually only encode strings when you're writing them to a file (or stdout). Most libraries (including nlpnet) deal with unicode strings.

To remove accents, you can use unicodedata (see https://gist.github.com/j4mie/557354). But nlpnet will not recognize correctly words with accents removed.
