### ISSUE TITLE
"This version of Mac-Morpho is contained in a single file for training and another for testing..." where could I find?

### ISSUE THREAD

**Issue by owlmsj** [erickrf/nlpnet#13]
Hi!

read in the docs that:

```
 "This version of Mac-Morpho is contained in a single file for training and another for testing, unlike the original distribution. Many errors were corrected and many sentences were discarded, providing a more reliable resource. Also unlike the original, each line contains a sentence, and POS tags are appended to tokens after a "_".

```

So, I see those files are no longer in the repo, where can I find them?  

Thanks and great job in nlpnet!

PS: http://www.nilc.icmc.usp.br/macmorpho/ is offline

**Comment by erickrf** [comment]
Thank you!

The corpus should be available in the URL you mentioned. There seems to be some problem with the server, though... I'll see if I can get it back online tomorrow.

**Comment by owlmsj** [comment]
Great! Waiting for it. Thanks again!

**Comment by erickrf** [comment]
The site is up now.

**Comment by tgalery** [comment]
Probably not the best place to ask this, but is there a big reason for the annotations to not use the peen treebank tags ?

**Comment by erickrf** [comment]
Penn Treebank tags were specifically designed for English; it wouldn't make sense to use them in another language. Mac-morpho uses a tagset tailored for Portuguese.
