### ISSUE TITLE
link to data

### ISSUE THREAD

**Issue by arademaker** [erickrf/nlpnet#15]
It was really non trivial to find the link to http://nilc.icmc.usp.br/macmorpho/. It would be interesting to have it explicited mentioned in the README.

**Comment by erickrf** [comment]
The MacMorpho corpus is independent from nlpnet (the system could be trained in any annotated corpus). The README file points to http://nilc.icmc.usp.br/nlpnet/models.html, where (currently) Portuguese and English models can be found.

**Comment by arademaker** [comment]
You are absolutely right, it makes sense. In the models page there is a link to MacMorpho as expected.
