### ISSUE TITLE
Python3.x Compatibility Version Development

### ISSUE THREAD

**Issue by ryukinix** [erickrf/nlpnet#19]
You have interest to make a python3.x version with this package? Now is not possible to use with python3.x and I wish we would can.

**Comment by erickrf** [comment]
I'd like that, but I don't use Python 3 and don't have much time to tweak nlpnet right now.

**Comment by robsonpeixoto** [comment]
News about it?

**Comment by erickrf** [comment]
Unfortunately not.

**Comment by robsonpeixoto** [comment]
Do you accept a PR, @erickrf? Or do you still without time?

**Comment by erickrf** [comment]
I can accept a PR, yes.

**Comment by Alshmowkh** [comment]
Who are you,please?

Alsmowkh

**Comment by miguellopes** [comment]
@erickrf I'm porting (or rather trying to) this package to python 3. I didn't test it with python 2, but after changing the pickle and izip imports, I can import the code on python 3 without errors but when I try to use the POSTagger it fails to find the pos-network.hdf5.
Where could I get that file? it's not on any of these files http://nilc.icmc.usp.br/nlpnet/data/

**Comment by erickrf** [comment]
Hi @miguellopes , thanks for the interest! Using hdf5 is a very recent addition to nlpnet (needed when dealing with files bigger than 4GB), and I intended to also allow numpy files to make it backwards compatible. So it looks like a bug; I'll check the code to make sure there's a proper fallback to numpy.

**Comment by erickrf** [comment]
@miguellopes fixed.
