### ISSUE TITLE
error on initial import

### ISSUE THREAD

**Issue by jstaker7** [erickrf/nlpnet#2]
I'd really like to try these scripts, but seem to hit a roadblock upfront.

Here is the traceback:

>>> import nlpnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nlpnet/__init__.py", line 3, in <module>
    import taggers
  File "nlpnet/taggers.py", line 17, in <module>
    from network import Network, ConvolutionalNetwork, LanguageModel
ImportError: No module named network

Here is the full build printout:

  Running setup.py install for nlpnet
    building 'nlpnet.network' extension
    gcc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -DNDEBUG -g -O3 -arch x86_64 -I. -I/Users/staker/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include -I/Applications/Canopy.app/appdata/canopy-1.2.0.1610.macosx-x86_64/Canopy.app/Contents/include/python2.7 -c nlpnet/network.c -o build/temp.macosx-10.6-x86_64-2.7/nlpnet/network.o
    In file included from nlpnet/network.c:346:
    In file included from /Users/staker/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/staker/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
    In file included from /Users/staker/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1760:
    /Users/staker/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    1 warning generated.
    gcc -bundle -undefined dynamic_lookup -g -arch x86_64 -L/tmp/_py/libraries/Applications/Canopy.app/appdata/canopy-1.2.0.1610.macosx-x86_64/Canopy.app/Contents/lib -headerpad_max_install_names -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/nlpnet/network.o -o build/lib.macosx-10.6-x86_64-2.7/nlpnet/network.so
    ld: warning: directory not found for option '-L/tmp/_py/libraries/Applications/Canopy.app/appdata/canopy-1.2.0.1610.macosx-x86_64/Canopy.app/Contents/lib'
    changing mode of build/scripts-2.7/nlpnet-tag.py from 644 to 755
    changing mode of build/scripts-2.7/nlpnet-train.py from 644 to 755
    changing mode of build/scripts-2.7/nlpnet-test.py from 644 to 755

    changing mode of /Users/staker/Library/Enthought/Canopy_64bit/User/bin/nlpnet-tag.py to 755
    changing mode of /Users/staker/Library/Enthought/Canopy_64bit/User/bin/nlpnet-test.py to 755
    changing mode of /Users/staker/Library/Enthought/Canopy_64bit/User/bin/nlpnet-train.py to 755
Successfully installed nlpnet

Can you help me understand what I might be missing here?

**Comment by andrecunha** [comment]
I think this might be solved with relative imports. Try changing:

`from network import Network, ConvolutionalNetwork`

to

`from .network import Network, ConvolutionalNetwork`

It worked for me. I will send a pull request later to change all sibling imports to relative imports.

**Comment by andrecunha** [comment]
By the way, @jstaker7 , it seems you are importing from the nlpnet folder of your current working directory, not from the site-packages folder where setuptools installed nlpnet. This won't work, since the network module is not compiled there. So, try to make the change that I mentioned in my previous comment (it's in file nlpnet/taggers.py), then run `python setup.py install` again, and make sure you are using the installed version, not the one from your current directory.

**Comment by edpittol** [comment]
Why the `nlpnet/network.pyd` file is ignored? See the `gitignore`.

**Comment by erickrf** [comment]
Because it is a binary file generated automatically during build.

2015-02-23 19:33 GMT-03:00 Eduardo Pittol <notifications@github.com>:

**Comment by papower1** [comment]
This happened to me again. (at newest version)

@andrecunha was right, I have to ```cd``` to another directory to fix that.
