### ISSUE TITLE
How to train new SRL model ?

### ISSUE THREAD

**Issue by GraphGrail** [erickrf/nlpnet#23]
Hi, nlpnet is cool, but i cannot find good tutorial on how to train my custom Semantic Role labeling model (language other than english). 
I read docs http://nilc.icmc.usp.br/nlpnet/training-srl.html and tried to reproduce, but first problem i faced is that there is no such file `nlpnet-train.py`.
I need to get new SRL model from text, so i tried to run in console:
`python train_srl.py srl pred --gold train_google.txt --data srl-model/`

where train_google.txt - is txt file with raw text, train_srl.py is file in \Lib\site-packages\nlpnet\srl\
But nothing happens, no errors, no new folder created
Am i right?

**Comment by erickrf** [comment]
Hi, you have to use `nlpnet-train.py`; `train_srl.py` doesn't train any models.

When you install nlpnet, `nlpnet-train.py` is copied from the bin/ directory to the `Scripts` folder of your Python installation or `/usr/local/bin`. If in Windows, are you sure it is in your PATH environment variable?

**Comment by GraphGrail** [comment]
Found it, close
