### ISSUE TITLE
Onde posso encontrar o significado das siglas?

### ISSUE THREAD

**Issue by jeffprestes** [erickrf/nlpnet#30]
Olá! 
Isso não é uma issue mas uma dúvida. Gostaria de saber onde posso encontrar um dicionário para as siglas que são retornadas pelo parser.
Por exemplo: VT = verbo.

Obrigado!

**Comment by erickrf** [comment]
Olá! Bom, aqui no github tem só o código da nlpnet, independente de modelo treinado. As tags usadas dependem dos dados usados. 

Se você estiver usando os modelos disponíveis para português e inglês na [documentação oficial](http://nilc.icmc.usp.br/nlpnet/models.html), posso ajudar. Qual tarefa especificamente (POS, SRL, parsing)?

**Comment by jeffprestes** [comment]
Olá Erick,

para começar, obrigado pela gentileza de responder as minhas dúvidas. Estou começando e minhas dúvidas devem soar básicas.
As tags POS que o NLPNET suporta são as mesmas que estão neste site: http://lxcenter.di.fc.ul.pt/tools/pt/LXTaggerPT.html , senão, onde posso encontrar?

Novamente, muito obrigado.

**Comment by erickrf** [comment]
Ok Jeff. A nlpnet em si suporta qualquer conjunto de tags, que ela aprende a partir do corpus em que for treinada. O conjunto de tags do LXTagger, até onde eu saiba, não existe em nenhum corpus disponível para treinar novos modelos, ou seja, é próprio dos desenvolvedores.

O conjunto usado com a nlpnet em português normalmente é o da terceira versão do [Mac-Morpho](http://nilc.icmc.usp.br/macmorpho/), que está no link que passei acima. Infelizmente, não sei de nenhum lugar onde haja uma tabela simples e atualizada com todas as tags, porque foram feitas pequenas alterações nelas na segunda e na terceira versão do corpus.

Existe o [manual](http://nilc.icmc.usp.br/macmorpho/macmorpho-manual.pdf) do Mac-Morpho original, que tem uma tabela com as tags no final. As diferenças dessas tags para as atuais é que 1) algumas não existem mais e 2) outras foram criadas para contrações como um merge de duas, p.ex. PREP+ART para contração de preposição e artigo.

Se você realmente quiser entender o que mudou de uma versão para a outra, tem [esse artigo](http://link.springer.com/article/10.1186/s13173-014-0020-x).

**Comment by jeffprestes** [comment]
Erick,

obrigado, agora já compreendi e localizei as tabelas de De -> Para.
E sim, estou pensando em usar o nlpnet para funções avançadas no meu Bot no Facebook Messenger. Vou fazer alguns testes com POS e SRL e talvez volte a fazer algumas perguntas.

Parabéns pelo projeto e mais uma vez obrigado!

**Comment by jeffprestes** [comment]
Erick,

obrigado pelas informações. Estamos trabalhando num wrapper do nlpnet para linguagem Go. Estamos tornando ele um webservice.
Porém ao pedir para ele executar uma analise SRL da expressão: ``` a roupa do rei de roma foi roida pelo rato``` um dos retornos é o codigo AM-MNR. Nos dois documentos supra citados por você não encontramos nada que possa nos esclarecer o que é AM-MNR. 
Achamos ser mister haver um HTML contendo uma tabela de correspondências entre os códigos. Assim ajudará muito os usuários do NLP net e quem tem interesse em usar uma ferramenta open source para fazer processamento de linguagem natural em português e de código aberto. Temos interesse em ajudá-lo nessa tarefa, sendo esse o espírito do código aberto e livre. Porém, para tanto, precisamos da colaboração de pessoas especialistas que saibam o que significa cada sigla.
Então peço-te dois favores:
a) pode nos esclarecer o que é AM-MNR?
b) quem poderíamos (pessoa + email) que poderíamos conversar para obter as informações sobre todas as siglas para gerar esse "dicionário" em HTML ?

Novamente muito obrigado!

**Comment by erickrf** [comment]
Olá, e desculpe pela demora em responder.

Bom, as tags de SRL são diferentes das de POS, pois vêm de projetos diferentes. As tags do modelo que você usou são do Propbank-BR, que são as mesmas do Propbank original em inglês. Mais informações sobre o projeto estão [no site](http://143.107.183.175:21380/portlex/index.php/en/downloadsingl), e o arquivo Tutorial contém as descrições das tags.

Respondendo:
a) AM-MNR é um argumento de modo (MNR sendo abreviado de manner). Aparentemente, foi um erro do modelo, porque muitas vezes os AM-MNR começam com "pelo".

b) Espero que os arquivos do projeto tenham informação suficiente. Algumas dúvidas pontuais eu mesmo posso responder.

De modo geral, você faz bem em apontar a escassez de informações sobre o significado das tags. Estamos acostumados com a maioria dos usuários de sistemas de NLP serem também pesquisadores de NLP e portanto familiarizados com nomenclaturas e tags, de modo que a documentação da nlpnet é dedicada somente ao funcionamento do código em si.

**Comment by jeffprestes** [comment]
Obrigado Erick. Tenho interesse em levar esse excelente de trabalho de vocês para fora da academia para beneficiar muita gente. Mandei uma mensagem a você no seu email da USP. 
Abraços!
