### ISSUE TITLE
Dependency parser for portuguese

### ISSUE THREAD

**Issue by gpassero** [erickrf/nlpnet#32]
It would be very useful to have a dependency parser also for portuguese, as described by @erickrf  in http://linguaecomputador.blogspot.com.br/2016/03/treinando-modelos-do-parser-de-stanford.html.

**Comment by erickrf** [comment]
The nlpnet parser model was created mostly in an experimental way and is not very good in comparison to the state of the art, neither in speed or accuracy. That's why I never bothered to publish a trained model. But maybe it could be useful for some reason, I'll have a look at it.

**Comment by erickrf** [comment]
Just for the record, nlpnet is not implementing any parser functionalities. There are some good implementations out there with trained models for Portuguese and many other languages (UDPipe, the new Stanford parser, Turku, COMBO, to name a few).
