### ISSUE TITLE
where to get the model for posTag for english ?

### ISSUE THREAD

**Issue by IvyGongoogle** [erickrf/nlpnet#34]
hello, the posTag model seems to be for Portuguese in  `http://nilc.icmc.usp.br/nlpnet/models.html` provided in your readme. but where to get the model for english for posTag? 

thank you in advance!

**Comment by erickrf** [comment]
The English model has both POS tagging and dependency parsing. It can also
be found in that URL.

Em 04/05/2017 11:44 AM, "AndrewGongoogle" <notifications@github.com>
escreveu:

**Comment by IvyGongoogle** [comment]
@erickrf  I found it! thank you!

**Comment by IvyGongoogle** [comment]
@erickrf Now I want to do SRL, but it is for Portuguese, where to get the model for english?

**Comment by erickrf** [comment]
I don't have a trained SRL model for English. You would have to train one.
