### ISSUE TITLE
problem on initial import

### ISSUE THREAD

**Issue by ValleyLad** [erickrf/nlpnet#37]
On install in Python 3.5 in Win10, can't seem to get around:

    running build_ext
    building 'nlpnet.network' extension
    error: [WinError 2] The system cannot find the file specified

**Comment by erickrf** [comment]
Did that happen after `python setup.py install`? 
Do you have a working installation of cython?

**Comment by ValleyLad** [comment]
(Thanks for the fast reply)
Yes it resulted upon doing: 
python setup.py install
And yes, the machine has working cython and working MinGW installs.

**Comment by erickrf** [comment]
This is weird. Right now I don't have a Windows machine, I'll try to check soon. But is there anything else in the error message?

**Comment by ValleyLad** [comment]
I repeated it a few times, re-starting Windows, etc. and unfortunately no different error messages.

**Comment by ValleyLad** [comment]
Found a way to get more error info -- so on doing:
python -m pip install nlpnet
I get the same errors as above, plus also:

Command "C:\Users\tmusg\AppData\Local\Programs\Python\Python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\tmusg\\AppData\\Local\\Temp\\pip-install-a5t9hnxz\\nlpnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\tmusg\AppData\Local\Temp\pip-record-pk3ubyml\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\tmusg\AppData\Local\Temp\pip-install-a5t9hnxz\nlpnet\

**Comment by ValleyLad** [comment]
Found a way to get more error info -- so on doing:
python -m pip install nlpnet
I get the same errors as above, plus also:

Command "C:\Users\super\AppData\Local\Programs\Python\Python35-32\python.exe -u -c "import setuptools, tokenize;file='C:\Users\super\AppData\Local\Temp\pip-install-a5t9hnxz\nlpnet\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record C:\Users\super\AppData\Local\Temp\pip-record-pk3ubyml\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\super\AppData\Local\Temp\pip-install-a5t9hnxz\nlpnet\

Googling this, there are a lot of people getting WinError 2 but not just with your package; rather with several others.  The combination of factors to create the problem seems to be:
Windows + Python 3.x + Cython
And it doesn't happen on *every* package invoking cython -- just some,
So I think this is probably *not* an issue with your package but an issue with getting Cython to work reliably on Windows and Python 3.X.
When I have time I will create a 2.7 Python install on the same WIndows machine and see if it can install nlpnet.  Meanwhile I'm closing this issue.
