### ISSUE TITLE
nlpnet install error

### ISSUE THREAD

**Issue by dauberson** [erickrf/nlpnet#45]
Hey guys, I am trying to install the nlpnet lib but I getting an error, someone can help me?

```
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qce58v27/nlpnet_5d97306497454c77a333d1e773fe5eb5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qce58v27/nlpnet_5d97306497454c77a333d1e773fe5eb5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p8umiw52
         cwd: /tmp/pip-install-qce58v27/nlpnet_5d97306497454c77a333d1e773fe5eb5/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qce58v27/nlpnet_5d97306497454c77a333d1e773fe5eb5/setup.py", line 1, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cc/3f/a5bf348da1a3148acb810d5236bd1c832383fd1a98cb9c4ac3f3bf92ab72/nlpnet-1.2.4.tar.gz#sha256=b791110ad068e273d2fc664d94b2608d322184da6b2cd799f0e4d476f1631614 (from https://pypi.org/simple/nlpnet/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement nlpnet==1.2.4 (from versions: 1.2.3.macosx-10.9-x86_64, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.2.1, 1.2.2, 1.2.4)
ERROR: No matching distribution found for nlpnet==1.2.4
```
And I have numpy installed v1.21.0

**Comment by erickrf** [comment]
How exactly did you install nlpnet? It seems that it was expecting a
specific version of numpy older than the one you have.

It's possible that nlpnet can work with a newer numpy version though.

Em ter, 13 de jul de 2021 02:50, dauberson ***@***.***>
escreveu:

**Comment by dauberson** [comment]
I'm using pip3 to try install nlpnet. 

`pip3 install nlpnet
Collecting nlpnet
  Using cached nlpnet-1.2.4.tar.gz (393 kB)
Requirement already satisfied: h5py>=2.8.0rc1 in ./.local/lib/python3.9/site-packages (from nlpnet) (3.3.0)
Requirement already satisfied: nltk>=3.2.2 in ./.local/lib/python3.9/site-packages (from nlpnet) (3.6.2)
Requirement already satisfied: numpy>=1.9.0 in /usr/lib/python3/dist-packages (from nlpnet) (1.19.5)
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from nlpnet) (1.15.0)
Requirement already satisfied: regex in ./.local/lib/python3.9/site-packages (from nltk>=3.2.2->nlpnet) (2021.7.6)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nltk>=3.2.2->nlpnet) (7.1.2)
Requirement already satisfied: joblib in ./.local/lib/python3.9/site-packages (from nltk>=3.2.2->nlpnet) (1.0.1)
Requirement already satisfied: tqdm in ./.local/lib/python3.9/site-packages (from nltk>=3.2.2->nlpnet) (4.56.2)
Building wheels for collected packages: nlpnet
  Building wheel for nlpnet (setup.py) ... error
`

**Comment by erickrf** [comment]
That reminds me I have not yet tested pip installation after the last
changes in the code :)

I will try to fix that soon. In the meantime, you can clone the repository
and install with python setup.py install.

Em qui, 15 de jul de 2021 04:48, dauberson ***@***.***>
escreveu:

**Comment by Lucas-Cerqueira** [comment]
@erickrf I opened the PR #46 that solves this numpy dependency issue when installing the package.

**Comment by erickrf** [comment]
@dauberson can you check if it works now with the new PR merged into the code?
