### ISSUE TITLE
nlpnet import error

### ISSUE THREAD

**Issue by OkFranco** [erickrf/nlpnet#48]
Hello, I was trying to install nlpnet but I faced this error. I already important the microsoft build tools, nltk and updated numpy. Still I cannot solve the error. Could you help me?

ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Public\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\franco joao\\AppData\\Local\\Temp\\pip-install-78011e7f\\nlpnet_72278bb9cbbe4b2f975dc611c37f0ed1\\setup.py'"'"'; __file__='"'"'C:\\Users\\franco joao\\AppData\\Local\\Temp\\pip-install-78011e7f\\nlpnet_72278bb9cbbe4b2f975dc611c37f0ed1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\franco joao\AppData\Local\Temp\pip-wheel-qe2xbz1r'
       cwd: C:\Users\franco joao\AppData\Local\Temp\pip-install-78011e7f\nlpnet_72278bb9cbbe4b2f975dc611c37f0ed1\
  Complete output (77 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\arguments.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\attributes.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\config.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\metadata.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\reader.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\taggers.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\utils.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\word_dictionary.py -> build\lib.win-amd64-3.9\nlpnet
  copying nlpnet\__init__.py -> build\lib.win-amd64-3.9\nlpnet
  creating build\lib.win-amd64-3.9\nlpnet\pos
  copying nlpnet\pos\macmorphoreader.py -> build\lib.win-amd64-3.9\nlpnet\pos
  copying nlpnet\pos\pos_reader.py -> build\lib.win-amd64-3.9\nlpnet\pos
  copying nlpnet\pos\__init__.py -> build\lib.win-amd64-3.9\nlpnet\pos
  creating build\lib.win-amd64-3.9\nlpnet\srl
  copying nlpnet\srl\srl_reader.py -> build\lib.win-amd64-3.9\nlpnet\srl
  copying nlpnet\srl\train_srl.py -> build\lib.win-amd64-3.9\nlpnet\srl
  copying nlpnet\srl\__init__.py -> build\lib.win-amd64-3.9\nlpnet\srl
  creating build\lib.win-amd64-3.9\nlpnet\parse
  copying nlpnet\parse\parse_reader.py -> build\lib.win-amd64-3.9\nlpnet\parse
  copying nlpnet\parse\__init__.py -> build\lib.win-amd64-3.9\nlpnet\parse
  running build_ext
  building 'nlpnet.network' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\nlpnet
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I. -IC:\Users\Public\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\Public\Anaconda3\include -IC:\Users\Public\Anaconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcnlpnet/network.c /Fobuild\temp.win-amd64-3.9\Release\nlpnet/network.obj
  network.c
  C:\Users\Public\Anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  nlpnet/network.c(10165): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  nlpnet/network.c(12317): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  nlpnet/network.c(13722): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
  nlpnet/network.c(23369): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  nlpnet/network.c(25504): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  nlpnet/network.c(26295): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  nlpnet/network.c(30836): warning C4305: '=': truncation from 'double' to 'float'
  nlpnet/network.c(33710): warning C4244: 'function': conversion from 'npy_intp' to 'long', possible loss of data
  nlpnet/network.c(33835): warning C4244: 'function': conversion from 'npy_intp' to 'long', possible loss of data
  nlpnet/network.c(36939): warning C4244: 'function': conversion from 'npy_intp' to 'long', possible loss of data
  nlpnet/network.c(37192): warning C4244: 'function': conversion from 'npy_intp' to 'long', possible loss of data
  nlpnet/network.c(37426): warning C4244: 'function': conversion from 'npy_intp' to 'long', possible loss of data
  nlpnet/network.c(37679): warning C4244: 'function': conversion from 'npy_intp' to 'long', possible loss of data
  nlpnet/network.c(44878): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
  nlpnet/network.c(57798): error C2039: 'tp_print': is not a member of '_typeobject'
  C:\Users\Public\Anaconda3\include\cpython/object.h(193): note: see declaration of '_typeobject'
  nlpnet/network.c(57819): error C2039: 'tp_print': is not a member of '_typeobject'
  C:\Users\Public\Anaconda3\include\cpython/object.h(193): note: see declaration of '_typeobject'
  nlpnet/network.c(57831): error C2039: 'tp_print': is not a member of '_typeobject'
  C:\Users\Public\Anaconda3\include\cpython/object.h(193): note: see declaration of '_typeobject'
  nlpnet/network.c(57840): error C2039: 'tp_print': is not a member of '_typeobject'
  C:\Users\Public\Anaconda3\include\cpython/object.h(193): note: see declaration of '_typeobject'

**Comment by erickrf** [comment]
Hi, sorry for the late reply, but I could not find the error. Unfortunately nlpnet is pretty outdated by now, so the issue might even be the cython version.

**Comment by OkFranco** [comment]
Hello Erick,

no problem.

It was indeed the python version.

Thanks!

Erick Fonseca ***@***.***> escreveu no dia segunda,
18/07/2022 à(s) 11:32:
