### ISSUE TITLE
NER with nlpnet

### ISSUE THREAD

**Issue by sam-gikian** [erickrf/nlpnet#6]
I am executing the first code snippet from  https://github.com/attardi/nlpnet. I am facing the following error:

AssertionError: Invalid data Directory.

Whereas I am providing the correct path to the data folder inside which is the \corpora.zip folder. So then why am I getting this error. I want to train nlpnet with my own corporas for Named Entity Recognition.

**Comment by attardi** [comment]
To train a NER please follow the instructions in the section Benchmarks
The other instructions refer to the use of the original NLPNET.

**Comment by kiran-surya** [comment]
While training nlpnet, i'm facing following error.
ValueError: all the input arrays must have same number of dimensions

**Comment by erickrf** [comment]
Any further questions about NER with nlpnet should be addressed to [attardi's repository](https://github.com/attardi/nlpnet) (or any other implementing it), since I never actually included this functionality in my code.

**Comment by attardi** [comment]
When people reported similar problems it was due to bad input data.
Please check your data: formatting, tab, utf8, etc.

—
