### ISSUE TITLE
Models page not found

### ISSUE THREAD

**Issue by edpittol** [erickrf/nlpnet#7]
I tried access http://nilc.icmc.usp.br/nlpnet/models.html. Appeared a 404 error.

**Comment by erickrf** [comment]
Yes, it is currently down. It should be normalized in the next few days.

2015-02-17 21:46 GMT-02:00 Eduardo Pittol <notifications@github.com>:

**Comment by erickrf** [comment]
It is in order now.

**Comment by edpittol** [comment]
For me not. Same error.

**Comment by erickrf** [comment]
Sorry, just double checked now. We are using an alias in our server to redirect http://nilc.icmc.usp.br/nlpnet to another port. You may access the documentation home directly and then navigate to the models page or access http://143.107.183.175:21580/nlpnet/models.html

**Comment by edpittol** [comment]
Ok. With this way, I could access the page. Thanks.
